### ISSUE TITLE
Driver not working on Universal Resolver public instance

### ISSUE THREAD

**Issue by BernhardFuchs** [KILTprotocol/kilt-did-driver#10]
When resolving the example DID did:kilt:5CqJa4Ct7oMeMESzehTiN9fwYdGLd7tqeirRMpGDh2XxYYyx from the [config](https://github.com/decentralized-identity/universal-resolver/blob/master/config.json), the driver throws following error:
```
🚀  KILT Resolver driver active on port 8080...
Fetching DID Document...
Error while querying services. Error: Got unexpected response from services.
    at /app/src/index.js:29:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Fetching DID Document...
Error while querying services. Error: Got unexpected response from services.
    at /app/src/index.js:29:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by weichweich** [comment]
Thanks for opening the issue! We are working on it. 🙂

**Comment by weichweich** [comment]
The example DID should work now. Thanks again for notifying us!
